CREATE DATABASE WISHLIST_SUPREMA;

CREATE TABLE DESENHOS(
     ID INT IDENTITY PRIMARY KEY
	 ,DESENHO TEXT NOT NULL
);

CREATE TABLE USUARIOS(
     ID INT IDENTITY PRIMARY KEY
	 ,EMAIL VARCHAR (250) NOT NULL
	 ,SENHA VARCHAR (250) NOT NULL  
);