CREATE DATABASE WISHLIST_SUPREMA;

CREATE TABLE DESEJOS(
     ID INT IDENTITY PRIMARY KEY
	 ,DATA_DO_DESEJO DATE NOT Null
	 ,DESEJO TEXT NOT NULL
);

CREATE TABLE USUARIOS(
     ID INT IDENTITY PRIMARY KEY
	 ,EMAIL VARCHAR (250) NOT NULL unique
	 ,SENHA VARCHAR (250) NOT NULL  
);